{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agentos-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if and .Values.ingress.tls.enabled .Values.web.host }}
  tls:
  - hosts:
    - {{ .Values.web.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - {{- if .Values.web.host }}
    host: {{ .Values.web.host }}
    {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-ui
            port:
              number: 5173
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-mock
            port:
              number: {{ index .Values.services "api" "port" }}
      - path: /policy
        pathType: Prefix
        backend:
          service:
            name: policy-mock
            port:
              number: {{ index .Values.services "policy" "port" }}
      - path: /otel
        pathType: Prefix
        backend:
          service:
            name: bridge-mock
            port:
              number: {{ index .Values.services "bridge" "port" }}
{{- end }}
