{{- range $service := list "runtime" "registry" "ingest" "api" "bridge" "policy" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service }}-mock
  namespace: {{ $.Release.Namespace }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"http": "api-backendconfig"}}'
spec:
  selector:
    app: {{ $service }}-mock
  ports:
  - name: http
    port: {{ index $.Values.services $service "port" }}
    targetPort: {{ index $.Values.services $service "port" }}
  type: ClusterIP
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"http": "web-backendconfig"}}'
spec:
  selector:
    app: web-ui
  ports:
  - name: http
    port: {{ .Values.web.port }}
    targetPort: {{ .Values.web.port }}
  type: ClusterIP
